### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by hawkiboy** [tjpin/pyplay#1]
Great stuff! But I have this error. I installed everything in a venv. (Any idea what is going on?)

pygame 2.5.2 (SDL 2.28.3, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/hawkibinkler/Downloads/pyplay-master/app.py", line 11, in <module>
    dialog = StartWindow()
             ^^^^^^^^^^^^^
  File "/Users/hawkibinkler/Downloads/pyplay-master/file_dialog.py", line 16, in __init__
    self.main = PyPlayer()
                ^^^^^^^^^^
  File "/Users/hawkibinkler/Downloads/pyplay-master/main.py", line 12, in __init__
    super(PyPlayer, self).__init__(parent=None)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by lazarus-muya** [comment]
This was a hobby project and no longer maintained.
Fixing this bug will raise other issues, therefore I would suggest waiting for my next release of similar but more complete and more professional project.
